version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - './backend:/var/www/html'
    

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    command: npm run dev
    container_name: mywebsite  

    image: docker-nextjs-dev 
    ports:
      - '3002:3000'
    volumes:
      - './frontend:/app'
    environment:
      -  WATCHPACK_POLLING=true  