version: '3'
services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/var/www/html
    networks:
      - booking_room_network

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - booking_room_network

networks:
  booking_room_network:

# explain:  
# định nghĩa 2 service: laravel và nextjs
# thư mục backend gắn kết vào /var/www/html, frontend ...
# cả 2 được kết nối vào mạng booking_room_network
  