version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bookung_room
      MYSQL_USER: root
      MYSQL_PASSWORD: 200019401a
      MYSQL_ROOT_PASSWORD: 200019401a
    volumes:
      - ./backend/mysql:/var/lib/mysql
